// @generated by js/scripts/generate-export-parity.mjs. Do not edit by hand:
// run `node js/scripts/generate-export-parity.mjs` after changing the public
// JavaScript or Rust surface.
//
// Requirement I195-PARITY-FEATURE-COMPLETENESS: every public export of
// js/src/index.js names the public Rust item that carries the same feature.
// The `use` items and method references below make the Rust build fail when
// one of those items disappears or stops being public, and the test checks
// that parity/language-features.json lists exactly the exports below.

use std::fs;
use std::path::PathBuf;

use serde_json::Value;

use super::issue_195_observations::{Observation, record};

/// Every public item a JavaScript export maps to, imported to prove it exists.
#[allow(unused_imports)]
mod items {
    use meta_language::API_OPERATIONS as _;
    use meta_language::AccessMode as _;
    use meta_language::ApiOperation as _;
    use meta_language::ApiOperationEntry as _;
    use meta_language::ApiStyle as _;
    use meta_language::ApiStyleCell as _;
    use meta_language::ApiStyleFixture as _;
    use meta_language::ByteRange as _;
    use meta_language::DECORATOR_LEVELS as _;
    use meta_language::Decorator as _;
    use meta_language::DecoratorError as _;
    use meta_language::DecoratorSet as _;
    use meta_language::EmbeddedRegion as _;
    use meta_language::EngineNetwork as _;
    use meta_language::ExprBuilder as _;
    use meta_language::FORMER_CONCEPT_ID_VOCABULARY as _;
    use meta_language::FORMER_CONCEPT_IDS as _;
    use meta_language::FOUR_LANGUAGE_SUPPORT as _;
    use meta_language::FluentPipeline as _;
    use meta_language::GRAMMAR_COMMAND_USAGE as _;
    use meta_language::GRAMMAR_DIAGNOSTIC_KINDS as _;
    use meta_language::GRAMMAR_EXPORT_FORMATS as _;
    use meta_language::GRAMMAR_IMPORT_FORMATS as _;
    use meta_language::GRAMMAR_LOSSLESS_FORMATS as _;
    use meta_language::GRAMMAR_LOWERING_FORMATS as _;
    use meta_language::GRAMMAR_MERGE_METHOD as _;
    use meta_language::GRAMMAR_ROUND_TRIP_MARKER as _;
    use meta_language::Grammar as _;
    use meta_language::GrammarBuilder as _;
    use meta_language::GrammarEmitError as _;
    use meta_language::GrammarImportError as _;
    use meta_language::GrammarLoweringError as _;
    use meta_language::GrammarMergeError as _;
    use meta_language::GrammarParseError as _;
    use meta_language::GrammarRenameError as _;
    use meta_language::GrammarRuntimeError as _;
    use meta_language::GraphQlAdapterError as _;
    use meta_language::GraphQlArgumentRole as _;
    use meta_language::GraphQlOperationType as _;
    use meta_language::GraphQlRootMapping as _;
    use meta_language::GraphQlSchemaRegistry as _;
    use meta_language::LANGUAGE_REPRESENTATION_SCHEMA_VERSION as _;
    use meta_language::LanguageProfile as _;
    use meta_language::LanguageProfileLinks as _;
    use meta_language::LanguageProfileViolation as _;
    use meta_language::Link as _;
    use meta_language::LinkCliSubstitution as _;
    use meta_language::LinkCliSubstitutionKind as _;
    use meta_language::LinkFlags as _;
    use meta_language::LinkId as _;
    use meta_language::LinkMetadata as _;
    use meta_language::LinkNetwork as _;
    use meta_language::LinkQuery as _;
    use meta_language::LinkRule as _;
    use meta_language::LinkRuleCapture as _;
    use meta_language::LinkRuleCaptures as _;
    use meta_language::LinkRuleMatch as _;
    use meta_language::LinkRuleParseError as _;
    use meta_language::LinkRuleRegistry as _;
    use meta_language::LinkRuleSnapshotCase as _;
    use meta_language::LinkRuleSnapshotExpectation as _;
    use meta_language::LinkRuleSnapshotReport as _;
    use meta_language::LinkRuleSnapshotResult as _;
    use meta_language::LinkRuleSnapshotSuite as _;
    use meta_language::LinkType as _;
    use meta_language::LoweredQueryPlan as _;
    use meta_language::MAX_LOWERED_CHARACTERS as _;
    use meta_language::NetworkProjection as _;
    use meta_language::NetworkSnapshot as _;
    use meta_language::PROGRAM_REPRESENTATION_SCHEMA_VERSION as _;
    use meta_language::PROGRAM_SNAPSHOT_SCHEMA_VERSION as _;
    use meta_language::ParseConfiguration as _;
    use meta_language::ParserRegistry as _;
    use meta_language::Point as _;
    use meta_language::ProbabilisticTruthValue as _;
    use meta_language::Probability as _;
    use meta_language::ProgramRepresentation as _;
    use meta_language::ProgramRepresentationError as _;
    use meta_language::QUERY_PLAN_VERSION as _;
    use meta_language::QueryAggregateFunction as _;
    use meta_language::QueryAuthorization as _;
    use meta_language::QueryCapture as _;
    use meta_language::QueryCaptures as _;
    use meta_language::QueryComparisonOperator as _;
    use meta_language::QueryIndex as _;
    use meta_language::QueryMatch as _;
    use meta_language::QueryOperation as _;
    use meta_language::QueryParseError as _;
    use meta_language::QueryPlan as _;
    use meta_language::QuerySortDirection as _;
    use meta_language::QuerySourceEvidence as _;
    use meta_language::REQUIRED_CONCEPT_DISTINCTIONS as _;
    use meta_language::REQUIRED_FOUNDATION_DISTINCTIONS as _;
    use meta_language::ReadOnlyNetwork as _;
    use meta_language::ReadOnlyViolation as _;
    use meta_language::RegionDetectionPolicy as _;
    use meta_language::RejectPredicateHost as _;
    use meta_language::ReplacementReport as _;
    use meta_language::ReplacementRule as _;
    use meta_language::RepresentationLevel as _;
    use meta_language::SELF_TRANSLATION_LANGUAGES as _;
    use meta_language::SEMANTIC_CONSTRUCTS as _;
    use meta_language::SEMANTIC_ENCODING as _;
    use meta_language::SEMANTIC_OBSERVATION as _;
    use meta_language::SQL_DIALECT_PROFILES as _;
    use meta_language::SelfTranslationError as _;
    use meta_language::SourceSpan as _;
    use meta_language::SourceTextPredicateHost as _;
    use meta_language::SqlAdapterError as _;
    use meta_language::SqlAdapterErrorKind as _;
    use meta_language::SqlRelationMapping as _;
    use meta_language::SqlSchemaRegistry as _;
    use meta_language::SubstitutionReport as _;
    use meta_language::SubstitutionRule as _;
    use meta_language::TextReplacement as _;
    use meta_language::TranslationRule as _;
    use meta_language::TranslationRuleSet as _;
    use meta_language::TranslationSupport as _;
    use meta_language::TranslationTemplate as _;
    use meta_language::TraversalReport as _;
    use meta_language::TraversalStrategy as _;
    use meta_language::TriviaAttachmentPolicy as _;
    use meta_language::TruthValue as _;
    use meta_language::VerificationIssue as _;
    use meta_language::VerificationReport as _;
    use meta_language::accepts_text as _;
    use meta_language::analyze_program as _;
    use meta_language::assert_merge_complete as _;
    use meta_language::assert_merge_shares as _;
    use meta_language::canonical_language_name as _;
    use meta_language::canonical_repeat as _;
    use meta_language::canonical_rule_definition as _;
    use meta_language::capture_grammar_layout as _;
    use meta_language::carry_rule_docs as _;
    use meta_language::check_concept_distinctions as _;
    use meta_language::check_grammar_lowering as _;
    use meta_language::check_grammar_reverse_conversion as _;
    use meta_language::check_grammar_round_trip as _;
    use meta_language::check_native_grammar_concepts as _;
    use meta_language::choice as _;
    use meta_language::compile_feature_grammar as _;
    use meta_language::concept_correspondence as _;
    use meta_language::concept_record as _;
    use meta_language::concept_records as _;
    use meta_language::concept_records_for_source_name as _;
    use meta_language::construct_program as _;
    use meta_language::construct_program_from_fragments as _;
    use meta_language::current_concept_id as _;
    use meta_language::decode_program_translation as _;
    use meta_language::decorate_grammar as _;
    use meta_language::decorate_syntax_tree as _;
    use meta_language::deserialize_grammar as _;
    use meta_language::detect_embedded_regions as _;
    use meta_language::detect_embedded_regions_in_tree as _;
    use meta_language::display_grammar_expression as _;
    use meta_language::dropped_grammar_features as _;
    use meta_language::emit_abnf as _;
    use meta_language::emit_antlr as _;
    use meta_language::emit_bnf as _;
    use meta_language::emit_ebnf as _;
    use meta_language::emit_gbnf as _;
    use meta_language::emit_grammar_lossless as _;
    use meta_language::emit_javascript_parser as _;
    use meta_language::emit_lark as _;
    use meta_language::emit_peggy as _;
    use meta_language::emit_pest as _;
    use meta_language::emit_tree_sitter_json as _;
    use meta_language::grammar_emitter as _;
    use meta_language::grammar_expr_concept_id as _;
    use meta_language::grammar_importer as _;
    use meta_language::grammar_names as _;
    use meta_language::grammar_precedence_concepts as _;
    use meta_language::grammar_provenance as _;
    use meta_language::import_abnf as _;
    use meta_language::import_antlr as _;
    use meta_language::import_bnf as _;
    use meta_language::import_ebnf as _;
    use meta_language::import_gbnf as _;
    use meta_language::import_grammar_lossless as _;
    use meta_language::import_lark as _;
    use meta_language::import_pest as _;
    use meta_language::import_tree_sitter_json as _;
    use meta_language::language_candidates_for_path as _;
    use meta_language::language_catalog as _;
    use meta_language::language_entry as _;
    use meta_language::language_for_path as _;
    use meta_language::language_support as _;
    use meta_language::lower_grammar as _;
    use meta_language::lower_graphql as _;
    use meta_language::lower_sql as _;
    use meta_language::merge_grammars as _;
    use meta_language::mutate_grammar_start_rule as _;
    use meta_language::native_construct_tree as _;
    use meta_language::native_grammar_concept_reuse as _;
    use meta_language::native_grammar_ids as _;
    use meta_language::native_grammar_language as _;
    use meta_language::native_grammar_rule_concepts as _;
    use meta_language::native_grammar_source as _;
    use meta_language::normalized_rule_definition as _;
    use meta_language::parse_grammar_layout_links as _;
    use meta_language::parse_grammar_links as _;
    use meta_language::parse_links_expression as _;
    use meta_language::parse_lowering_metadata as _;
    use meta_language::parse_native_grammar as _;
    use meta_language::parse_with_grammar as _;
    use meta_language::percent_decode_links_text as _;
    use meta_language::percent_encode_links_text as _;
    use meta_language::query_by_concept_term as _;
    use meta_language::read_translation_provenance as _;
    use meta_language::reconstruct_grammar as _;
    use meta_language::rename_grammar_rule as _;
    use meta_language::render_declaration_links as _;
    use meta_language::render_grammar_layout_links as _;
    use meta_language::render_grammar_links as _;
    use meta_language::render_links_expression as _;
    use meta_language::render_lowering_metadata as _;
    use meta_language::render_native_expression as _;
    use meta_language::render_native_grammar as _;
    use meta_language::render_rule_fields as _;
    use meta_language::render_rule_link as _;
    use meta_language::restore_source_names as _;
    use meta_language::run_api_style_fixture as _;
    use meta_language::run_grammar_command as _;
    use meta_language::script_language as _;
    use meta_language::self_translate as _;
    use meta_language::self_translation_language as _;
    use meta_language::self_translation_signatures as _;
    use meta_language::sequence as _;
    use meta_language::serialize_grammar as _;
    use meta_language::shared_rule_decisions as _;
    use meta_language::sniff_language as _;
    use meta_language::source_meanings_in as _;
    use meta_language::split_grammar_source as _;
    use meta_language::translate_native_construct as _;
    use meta_language::translate_native_construct_tree as _;
    use meta_language::translate_program as _;
    use meta_language::translation_contract as _;
    use meta_language::translation_contracts as _;
    use meta_language::validate as _;
}

/// Every JavaScript export as `(export, Rust path, kind)`.
const EXPORTS: &[(&str, &str, &str)] = &[
    ("API_OPERATIONS", "API_OPERATIONS", "constant"),
    ("AccessMode", "AccessMode", "type"),
    ("ApiOperation", "ApiOperation", "type"),
    ("ApiOperationEntry", "ApiOperationEntry", "type"),
    ("ApiStyle", "ApiStyle", "type"),
    ("ApiStyleCell", "ApiStyleCell", "type"),
    ("ApiStyleFixture", "ApiStyleFixture", "type"),
    ("ApiStyleFixtureKind", "ApiStyleFixture", "type"),
    ("BindingRenameError", "ProgramRepresentationError", "type"),
    ("ByteRange", "ByteRange", "type"),
    ("CONCEPT_RECORDS", "concept_records", "function"),
    ("DECORATOR_LEVELS", "DECORATOR_LEVELS", "constant"),
    ("DecoratorError", "DecoratorError", "type"),
    ("DecoratorSet", "DecoratorSet", "type"),
    ("EmbeddedRegion", "EmbeddedRegion", "type"),
    ("EngineNetwork", "EngineNetwork", "type"),
    ("ExprBuilder", "ExprBuilder", "type"),
    ("FORMER_CONCEPT_IDS", "FORMER_CONCEPT_IDS", "constant"),
    (
        "FORMER_CONCEPT_ID_VOCABULARY",
        "FORMER_CONCEPT_ID_VOCABULARY",
        "constant",
    ),
    ("FluentPipeline", "FluentPipeline", "type"),
    ("GRAMMAR_COMMAND_USAGE", "GRAMMAR_COMMAND_USAGE", "constant"),
    (
        "GRAMMAR_DIAGNOSTIC_KINDS",
        "GRAMMAR_DIAGNOSTIC_KINDS",
        "constant",
    ),
    (
        "GRAMMAR_EXPORT_FORMATS",
        "GRAMMAR_EXPORT_FORMATS",
        "constant",
    ),
    (
        "GRAMMAR_IMPORT_FORMATS",
        "GRAMMAR_IMPORT_FORMATS",
        "constant",
    ),
    (
        "GRAMMAR_LOSSLESS_FORMATS",
        "GRAMMAR_LOSSLESS_FORMATS",
        "constant",
    ),
    (
        "GRAMMAR_LOWERING_FORMATS",
        "GRAMMAR_LOWERING_FORMATS",
        "constant",
    ),
    ("GRAMMAR_MERGE_METHOD", "GRAMMAR_MERGE_METHOD", "constant"),
    (
        "GRAMMAR_ROUND_TRIP_MARKER",
        "GRAMMAR_ROUND_TRIP_MARKER",
        "constant",
    ),
    ("Grammar", "Grammar", "type"),
    ("GrammarBuilder", "GrammarBuilder", "type"),
    ("GrammarEmitError", "GrammarEmitError", "type"),
    ("GrammarImportError", "GrammarImportError", "type"),
    ("GrammarLoweringError", "GrammarLoweringError", "type"),
    ("GrammarMergeError", "GrammarMergeError", "type"),
    ("GrammarParseError", "GrammarParseError", "type"),
    ("GrammarRenameError", "GrammarRenameError", "type"),
    ("GrammarRuntimeError", "GrammarRuntimeError", "type"),
    ("GraphQlAdapterError", "GraphQlAdapterError", "type"),
    ("GraphQlArgumentRole", "GraphQlArgumentRole", "type"),
    ("GraphQlOperationType", "GraphQlOperationType", "type"),
    ("GraphQlRootMapping", "GraphQlRootMapping", "type"),
    ("GraphQlSchemaRegistry", "GraphQlSchemaRegistry", "type"),
    ("LANGUAGE_CATALOG", "language_catalog", "function"),
    (
        "LANGUAGE_REPRESENTATION_SCHEMA_VERSION",
        "LANGUAGE_REPRESENTATION_SCHEMA_VERSION",
        "constant",
    ),
    ("LanguageProfile", "LanguageProfile", "type"),
    ("LanguageProfileLinks", "LanguageProfileLinks", "type"),
    (
        "LanguageProfileViolation",
        "LanguageProfileViolation",
        "type",
    ),
    ("Link", "Link", "type"),
    ("LinkCliSubstitution", "LinkCliSubstitution", "type"),
    ("LinkCliSubstitutionKind", "LinkCliSubstitutionKind", "type"),
    ("LinkFlags", "LinkFlags", "type"),
    ("LinkId", "LinkId", "type"),
    ("LinkMetadata", "LinkMetadata", "type"),
    ("LinkNetwork", "LinkNetwork", "type"),
    ("LinkQuery", "LinkQuery", "type"),
    ("LinkRule", "LinkRule", "type"),
    ("LinkRuleCapture", "LinkRuleCapture", "type"),
    ("LinkRuleCaptures", "LinkRuleCaptures", "type"),
    ("LinkRuleMatch", "LinkRuleMatch", "type"),
    ("LinkRuleParseError", "LinkRuleParseError", "type"),
    ("LinkRuleRegistry", "LinkRuleRegistry", "type"),
    ("LinkRuleSnapshotCase", "LinkRuleSnapshotCase", "type"),
    (
        "LinkRuleSnapshotExpectation",
        "LinkRuleSnapshotExpectation",
        "type",
    ),
    ("LinkRuleSnapshotReport", "LinkRuleSnapshotReport", "type"),
    ("LinkRuleSnapshotResult", "LinkRuleSnapshotResult", "type"),
    ("LinkRuleSnapshotSuite", "LinkRuleSnapshotSuite", "type"),
    ("LinkType", "LinkType", "type"),
    ("LoweredQueryPlan", "LoweredQueryPlan", "type"),
    (
        "MAX_LOWERED_CHARACTERS",
        "MAX_LOWERED_CHARACTERS",
        "constant",
    ),
    ("NetworkProjection", "NetworkProjection", "type"),
    ("NetworkSnapshot", "NetworkSnapshot", "type"),
    (
        "PROGRAM_REPRESENTATION_SCHEMA_VERSION",
        "PROGRAM_REPRESENTATION_SCHEMA_VERSION",
        "constant",
    ),
    (
        "PROGRAM_SNAPSHOT_SCHEMA_VERSION",
        "PROGRAM_SNAPSHOT_SCHEMA_VERSION",
        "constant",
    ),
    ("ParseConfiguration", "ParseConfiguration", "type"),
    ("ParserRegistry", "ParserRegistry", "type"),
    ("Point", "Point", "type"),
    ("ProbabilisticTruthValue", "ProbabilisticTruthValue", "type"),
    ("Probability", "Probability", "type"),
    ("ProgramRepresentation", "ProgramRepresentation", "type"),
    (
        "ProgramTransformationError",
        "ProgramRepresentationError",
        "type",
    ),
    ("QUERY_PLAN_VERSION", "QUERY_PLAN_VERSION", "constant"),
    ("QueryAggregateFunction", "QueryAggregateFunction", "type"),
    ("QueryAuthorization", "QueryAuthorization", "type"),
    ("QueryCapture", "QueryCapture", "type"),
    ("QueryCaptures", "QueryCaptures", "type"),
    ("QueryComparisonOperator", "QueryComparisonOperator", "type"),
    ("QueryIndex", "QueryIndex", "type"),
    ("QueryMatch", "QueryMatch", "type"),
    ("QueryOperation", "QueryOperation", "type"),
    ("QueryParseError", "QueryParseError", "type"),
    ("QueryPlan", "QueryPlan", "type"),
    ("QuerySortDirection", "QuerySortDirection", "type"),
    ("QuerySourceEvidence", "QuerySourceEvidence", "type"),
    (
        "REQUIRED_CONCEPT_DISTINCTIONS",
        "REQUIRED_CONCEPT_DISTINCTIONS",
        "constant",
    ),
    (
        "REQUIRED_FOUNDATION_DISTINCTIONS",
        "REQUIRED_FOUNDATION_DISTINCTIONS",
        "constant",
    ),
    ("ReadOnlyNetwork", "ReadOnlyNetwork", "type"),
    ("ReadOnlyViolation", "ReadOnlyViolation", "type"),
    ("RegionDetectionPolicy", "RegionDetectionPolicy", "type"),
    ("ReplacementReport", "ReplacementReport", "type"),
    ("ReplacementRule", "ReplacementRule", "type"),
    ("RepresentationLevel", "RepresentationLevel", "type"),
    (
        "SELF_TRANSLATION_LANGUAGES",
        "SELF_TRANSLATION_LANGUAGES",
        "constant",
    ),
    ("SEMANTIC_CONSTRUCTS", "SEMANTIC_CONSTRUCTS", "constant"),
    ("SEMANTIC_ENCODING", "SEMANTIC_ENCODING", "constant"),
    ("SEMANTIC_OBSERVATION", "SEMANTIC_OBSERVATION", "constant"),
    ("SQL_DIALECT_PROFILES", "SQL_DIALECT_PROFILES", "constant"),
    ("SelfTranslationError", "SelfTranslationError", "type"),
    ("SourceSpan", "SourceSpan", "type"),
    ("SqlAdapterError", "SqlAdapterError", "type"),
    ("SqlAdapterErrorKind", "SqlAdapterErrorKind", "type"),
    ("SqlRelationMapping", "SqlRelationMapping", "type"),
    ("SqlSchemaRegistry", "SqlSchemaRegistry", "type"),
    ("SubstitutionReport", "SubstitutionReport", "type"),
    ("SubstitutionRule", "SubstitutionRule", "type"),
    ("TextReplacement", "TextReplacement", "type"),
    ("TranslationRule", "TranslationRule", "type"),
    ("TranslationRuleSet", "TranslationRuleSet", "type"),
    ("TranslationSupport", "TranslationSupport", "type"),
    ("TranslationTemplate", "TranslationTemplate", "type"),
    ("TraversalReport", "TraversalReport", "type"),
    ("TraversalStrategy", "TraversalStrategy", "type"),
    ("TriviaAttachmentPolicy", "TriviaAttachmentPolicy", "type"),
    ("TruthValue", "TruthValue", "type"),
    ("VerificationIssue", "VerificationIssue", "type"),
    ("VerificationReport", "VerificationReport", "type"),
    ("acceptsText", "accepts_text", "function"),
    ("accessModeIsMutable", "AccessMode::is_mutable", "method"),
    ("accessModeIsReadOnly", "AccessMode::is_read_only", "method"),
    ("accessModeLabel", "AccessMode::label", "method"),
    ("analyzeProgram", "analyze_program", "function"),
    ("analyze_program", "analyze_program", "function"),
    ("asReadOnly", "LinkNetwork::as_read_only", "method"),
    ("as_read_only", "LinkNetwork::as_read_only", "method"),
    ("assertMergeComplete", "assert_merge_complete", "function"),
    ("assertMergeShares", "assert_merge_shares", "function"),
    (
        "canonicalLanguageName",
        "canonical_language_name",
        "function",
    ),
    ("canonicalRepeat", "canonical_repeat", "function"),
    (
        "canonicalRuleDefinition",
        "canonical_rule_definition",
        "function",
    ),
    ("captureGrammarLayout", "capture_grammar_layout", "function"),
    ("carryRuleDocs", "carry_rule_docs", "function"),
    (
        "checkConceptDistinctions",
        "check_concept_distinctions",
        "function",
    ),
    ("checkGrammarLowering", "check_grammar_lowering", "function"),
    (
        "checkGrammarReverseConversion",
        "check_grammar_reverse_conversion",
        "function",
    ),
    (
        "checkGrammarRoundTrip",
        "check_grammar_round_trip",
        "function",
    ),
    (
        "checkNativeGrammarConcepts",
        "check_native_grammar_concepts",
        "function",
    ),
    ("choice", "choice", "function"),
    ("compileGrammar", "compile_feature_grammar", "function"),
    (
        "conceptCorrespondence",
        "concept_correspondence",
        "function",
    ),
    ("conceptRecord", "concept_record", "function"),
    ("conceptRecords", "concept_records", "function"),
    (
        "conceptRecordsForSourceName",
        "concept_records_for_source_name",
        "function",
    ),
    ("constructProgram", "construct_program", "function"),
    (
        "constructProgramFromFragments",
        "construct_program_from_fragments",
        "function",
    ),
    ("createGrammarParser", "compile_feature_grammar", "function"),
    (
        "createProgramSnapshot",
        "ProgramRepresentation::serialize_snapshot",
        "method",
    ),
    ("currentConceptId", "current_concept_id", "function"),
    (
        "decodeProgramTranslation",
        "decode_program_translation",
        "function",
    ),
    ("decorateGrammar", "decorate_grammar", "function"),
    ("decorateSyntaxTree", "decorate_syntax_tree", "function"),
    ("decorator", "Decorator", "type"),
    ("decoratorSet", "DecoratorSet", "type"),
    ("deserializeGrammar", "deserialize_grammar", "function"),
    (
        "detectEmbeddedRegions",
        "detect_embedded_regions",
        "function",
    ),
    (
        "detectEmbeddedRegionsInTree",
        "detect_embedded_regions_in_tree",
        "function",
    ),
    (
        "displayGrammarExpression",
        "display_grammar_expression",
        "function",
    ),
    (
        "droppedGrammarFeatures",
        "dropped_grammar_features",
        "function",
    ),
    ("emitAbnf", "emit_abnf", "function"),
    ("emitAntlr", "emit_antlr", "function"),
    ("emitBnf", "emit_bnf", "function"),
    ("emitEbnf", "emit_ebnf", "function"),
    ("emitGbnf", "emit_gbnf", "function"),
    ("emitGrammarLossless", "emit_grammar_lossless", "function"),
    ("emitJavascriptParser", "emit_javascript_parser", "function"),
    ("emitLark", "emit_lark", "function"),
    ("emitPeggy", "emit_peggy", "function"),
    ("emitPest", "emit_pest", "function"),
    ("emitTreeSitterJson", "emit_tree_sitter_json", "function"),
    ("emit_abnf", "emit_abnf", "function"),
    ("emit_antlr", "emit_antlr", "function"),
    ("emit_bnf", "emit_bnf", "function"),
    ("emit_ebnf", "emit_ebnf", "function"),
    ("emit_gbnf", "emit_gbnf", "function"),
    ("emit_lark", "emit_lark", "function"),
    ("emit_pest", "emit_pest", "function"),
    ("emit_tree_sitter_json", "emit_tree_sitter_json", "function"),
    ("fourLanguageSupport", "FOUR_LANGUAGE_SUPPORT", "constant"),
    ("freeze", "LinkNetwork::freeze", "method"),
    ("grammarEmitter", "grammar_emitter", "function"),
    (
        "grammarExprConceptId",
        "grammar_expr_concept_id",
        "function",
    ),
    ("grammarImporter", "grammar_importer", "function"),
    ("grammarNames", "grammar_names", "function"),
    (
        "grammarPrecedenceConcepts",
        "grammar_precedence_concepts",
        "function",
    ),
    ("grammarProvenance", "grammar_provenance", "function"),
    ("idKey", "LinkId::as_u64", "method"),
    ("importAbnf", "import_abnf", "function"),
    ("importAntlr", "import_antlr", "function"),
    ("importBnf", "import_bnf", "function"),
    ("importEbnf", "import_ebnf", "function"),
    ("importGbnf", "import_gbnf", "function"),
    (
        "importGrammarLossless",
        "import_grammar_lossless",
        "function",
    ),
    ("importLark", "import_lark", "function"),
    ("importPest", "import_pest", "function"),
    (
        "importTreeSitterJson",
        "import_tree_sitter_json",
        "function",
    ),
    ("import_abnf", "import_abnf", "function"),
    ("import_antlr", "import_antlr", "function"),
    ("import_bnf", "import_bnf", "function"),
    ("import_ebnf", "import_ebnf", "function"),
    ("import_gbnf", "import_gbnf", "function"),
    ("import_lark", "import_lark", "function"),
    ("import_pest", "import_pest", "function"),
    (
        "import_tree_sitter_json",
        "import_tree_sitter_json",
        "function",
    ),
    (
        "insertConceptRecord",
        "LinkNetwork::insert_concept_record",
        "method",
    ),
    (
        "languageCandidatesForPath",
        "language_candidates_for_path",
        "function",
    ),
    ("languageEntry", "language_entry", "function"),
    ("languageForPath", "language_for_path", "function"),
    ("languageSupport", "language_support", "function"),
    ("lowerGrammar", "lower_grammar", "function"),
    ("lowerGraphQL", "lower_graphql", "function"),
    ("lowerGraphQl", "lower_graphql", "function"),
    ("lowerGraphql", "lower_graphql", "function"),
    ("lowerSQL", "lower_sql", "function"),
    ("lowerSql", "lower_sql", "function"),
    ("lower_sql", "lower_sql", "function"),
    ("mergeGrammars", "merge_grammars", "function"),
    (
        "mutateGrammarStartRule",
        "mutate_grammar_start_rule",
        "function",
    ),
    ("nativeConstructTree", "native_construct_tree", "function"),
    (
        "nativeGrammarConceptReuse",
        "native_grammar_concept_reuse",
        "function",
    ),
    ("nativeGrammarIds", "native_grammar_ids", "function"),
    (
        "nativeGrammarLanguage",
        "native_grammar_language",
        "function",
    ),
    (
        "nativeGrammarRuleConcepts",
        "native_grammar_rule_concepts",
        "function",
    ),
    ("nativeGrammarSource", "native_grammar_source", "function"),
    (
        "normalizedRuleDefinition",
        "normalized_rule_definition",
        "function",
    ),
    ("parseEngine", "LinkNetwork::parse_engine", "method"),
    (
        "parseGrammarLayoutLinks",
        "parse_grammar_layout_links",
        "function",
    ),
    ("parseGrammarLinks", "parse_grammar_links", "function"),
    ("parseLinksExpression", "parse_links_expression", "function"),
    (
        "parseLoweringMetadata",
        "parse_lowering_metadata",
        "function",
    ),
    ("parseNativeGrammar", "parse_native_grammar", "function"),
    ("parseWithGrammar", "parse_with_grammar", "function"),
    ("parse_engine", "LinkNetwork::parse_engine", "method"),
    (
        "percentDecodeLinksText",
        "percent_decode_links_text",
        "function",
    ),
    (
        "percentEncodeLinksText",
        "percent_encode_links_text",
        "function",
    ),
    ("queryByConceptTerm", "query_by_concept_term", "function"),
    (
        "readProgramSnapshot",
        "ProgramRepresentation::from_snapshot",
        "method",
    ),
    (
        "readTranslationProvenance",
        "read_translation_provenance",
        "function",
    ),
    ("reconstructGrammar", "reconstruct_grammar", "function"),
    ("rejectPredicateHost", "RejectPredicateHost", "type"),
    ("renameGrammarRule", "rename_grammar_rule", "function"),
    (
        "renderDeclarationLinks",
        "render_declaration_links",
        "function",
    ),
    (
        "renderGrammarLayoutLinks",
        "render_grammar_layout_links",
        "function",
    ),
    ("renderGrammarLinks", "render_grammar_links", "function"),
    (
        "renderLinksExpression",
        "render_links_expression",
        "function",
    ),
    (
        "renderLoweringMetadata",
        "render_lowering_metadata",
        "function",
    ),
    (
        "renderNativeExpression",
        "render_native_expression",
        "function",
    ),
    ("renderNativeGrammar", "render_native_grammar", "function"),
    ("renderRuleFieldLinks", "render_rule_fields", "function"),
    ("renderRuleLink", "render_rule_link", "function"),
    ("renderSyntaxTree", "SyntaxTree::render", "method"),
    ("restoreSourceNames", "restore_source_names", "function"),
    ("runApiStyleFixture", "run_api_style_fixture", "function"),
    ("runGrammarCommand", "run_grammar_command", "function"),
    ("scriptLanguage", "script_language", "function"),
    ("selfTranslate", "self_translate", "function"),
    (
        "selfTranslationLanguage",
        "self_translation_language",
        "function",
    ),
    (
        "selfTranslationSignatures",
        "self_translation_signatures",
        "function",
    ),
    ("sequence", "sequence", "function"),
    ("serializeGrammar", "serialize_grammar", "function"),
    ("sharedRuleDecisions", "shared_rule_decisions", "function"),
    ("sniffLanguage", "sniff_language", "function"),
    ("sourceMeanings", "source_meanings_in", "function"),
    ("sourceTextPredicateHost", "SourceTextPredicateHost", "type"),
    ("splitGrammarSource", "split_grammar_source", "function"),
    (
        "translateNativeConstruct",
        "translate_native_construct",
        "function",
    ),
    (
        "translateNativeConstructTree",
        "translate_native_construct_tree",
        "function",
    ),
    ("translateProgram", "translate_program", "function"),
    ("translationContract", "translation_contract", "function"),
    ("translationContracts", "translation_contracts", "function"),
    ("validateGrammar", "validate", "function"),
];

const FIXTURE_ID: &str = "planned:repository-directive:i195-parity-feature-completeness";

fn language_features() -> Value {
    let mut dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    while !dir.join("parity/language-features.json").is_file() {
        assert!(dir.pop(), "parity/language-features.json should exist");
    }
    let text = fs::read_to_string(dir.join("parity/language-features.json"))
        .expect("parity/language-features.json should be readable");
    serde_json::from_str(&text).expect("parity/language-features.json should be JSON")
}

#[test]
fn export_parity_rust_has_every_listed_feature() {
    let _ = meta_language::AccessMode::is_mutable;
    let _ = meta_language::AccessMode::is_read_only;
    let _ = meta_language::AccessMode::label;
    let _ = meta_language::LinkId::as_u64;
    let _ = meta_language::LinkNetwork::as_read_only;
    let _ = meta_language::LinkNetwork::freeze;
    let _ = meta_language::LinkNetwork::insert_concept_record;
    let _ = meta_language::LinkNetwork::parse_engine;
    let _ = meta_language::ProgramRepresentation::from_snapshot;
    let _ = meta_language::ProgramRepresentation::serialize_snapshot;
    let _ = meta_language::SyntaxTree::render;
    let features = language_features();
    let listed = features["javascriptExports"]
        .as_object()
        .expect("javascriptExports should be an object");
    assert_eq!(listed.len(), EXPORTS.len(), "each export is listed");
    for (name, rust, kind) in EXPORTS {
        let entry = &listed[*name];
        assert_eq!(entry["rust"], *rust, "{name} maps to {rust}");
        assert_eq!(entry["kind"], *kind, "{name} is a {kind}");
    }
    record(&Observation {
        requirement_id: "I195-PARITY-FEATURE-COMPLETENESS",
        suffix: "behavior",
        fixture_id: FIXTURE_ID,
        fixture_file: "docs/vision.md",
        assertions: &["everyPublicExportListed", "rustHasEveryFeature"],
        test_name: "javascript_export_parity::export_parity_rust_has_every_listed_feature",
    });
}
