import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';
import { contentScanner, scannerFamilies } from '../scripts/scanner-families.mjs';
import { compileGrammar, parseGrammarLinks, renderSyntaxTree } from '../src/index.js';
import { importTreeSitterNative, renderTreeSitterNative } from '../src/grammar-importers/tree-sitter-native.js';
import { recordIssue195Observations } from './support/issue-195-observations.js';

const fixtureGroups = [
  ['parity/fixtures/scanner-delimiter-runs.json', 'I195-GRAMMAR-SCANNER-DELIMITER-RUNS'],
  ['parity/fixtures/scanner-families.json', 'I195-GRAMMAR-SCANNER-DELIMITER-FAMILIES'],
  ['parity/fixtures/scanner-counted-delimiters.json', 'I195-GRAMMAR-SCANNER-COUNTED-DELIMITERS'],
];
const fixtures = fixtureGroups.flatMap(([fixtureFile, requirementId]) => JSON.parse(readFileSync(new URL(`../../${fixtureFile}`, import.meta.url), 'utf8')).map((item) => ({ ...item, fixtureFile, requirementId })));
for (const fixture of fixtures) {
  test(`scanner family ${fixture.name} preserves text and rejects truncated delimiters`, () => {
    assert.equal(scannerFamilies(fixture.scanners), fixture.generated);
    const parser = compileGrammar(parseGrammarLinks(fixture.listing));
    for (const input of fixture.accept) {
      const outcome = parser.parseTree(input);
      assert.equal(outcome.ok, true, JSON.stringify({ input, rejection: outcome.rejection }));
      assert.equal(outcome.tree.start, 0);
      assert.equal(outcome.tree.end, Buffer.byteLength(input));
      const texts = (node) => node.type === 'token' ? node.text : node.children.map(texts).join('');
      assert.equal(texts(outcome.tree), input);
      assert.equal(renderSyntaxTree(outcome.tree), fixture.trees[input]);
    }
    for (const input of fixture.reject) assert.equal(parser.parseTree(input).ok, false, input);
    recordIssue195Observations({
      requirementId: fixture.requirementId, suffix: 'behavior',
      fixtureId: `planned:repository-directive:${fixture.requirementId.toLowerCase()}`,
      fixtureFile: fixture.fixtureFile, assertions: [fixture.assertion],
      testName: `scanner family ${fixture.name} preserves text and rejects truncated delimiters`,
    });
  });
}

test('scanner families satisfy tree-sitter external declarations through executable grammar data', () => {
  const fixture = fixtures.find((item) => item.name === 'nested comments');
  const grammar = {
    name: 'comments', externals: [{ type: 'SYMBOL', name: 'comment' }],
    rules: { source: { type: 'REPEAT1', content: { type: 'SYMBOL', name: 'comment' } } },
  };
  const imported = importTreeSitterNative(grammar, { scanners: scannerFamilies(fixture.scanners), immediate: ['comment'] });
  assert.equal(imported.scanners.length, 1);
  assert.deepEqual(imported.report.unsupported, []);
  const parser = compileGrammar(parseGrammarLinks(renderTreeSitterNative(imported)));
  assert.equal(parser.parseTree('/*a/*b*/c*/').ok, true);
  assert.equal(parser.parseTree('/*a/*b*/').ok, false);
});

test('scanner family descriptors reject invalid and ambiguous definitions', () => {
  const descriptor = { family: 'delimited', name: 'comments', token: 'comment', opening: '/*', closing: '*/' };
  for (const field of ['name', 'token']) assert.throws(() => scannerFamilies([{ ...descriptor, [field]: ') fail (' }]), TypeError);
  assert.throws(() => scannerFamilies([{ ...descriptor, opening: '' }]), TypeError);
  assert.throws(() => scannerFamilies([{ ...descriptor, opening: '"', closing: '"', nested: true }]), TypeError);
  assert.throws(() => scannerFamilies([descriptor, descriptor]), TypeError);
  assert.throws(() => scannerFamilies([{ ...descriptor, family: 'host callback' }]), TypeError);
  assert.throws(() => scannerFamilies([{ family: 'content', name: 'strings', token: 'string', closeToken: 'string', closing: '"' }]), TypeError);
  const split = { family: 'split-counted-delimiter', name: 'blocks', startToken: 'start', contentToken: 'content', endToken: 'end', prefix: '[', marker: '=', opening: '[', closing: ']', suffix: ']' };
  for (const countModulo of [0, 1, 2.5, Infinity, '256']) assert.throws(() => scannerFamilies([{ ...split, countModulo }]), TypeError);
  assert.throws(() => scannerFamilies([{ ...split, endToken: 'start' }]), TypeError);
  assert.throws(() => scannerFamilies([{ ...split, contentStops: [''] }]), TypeError);
});

test('the shipped Rust string scanner is generated by the common content family', () => {
  const generated = contentScanner({ name: 'strings', token: 'string_content', closeToken: 'string_close', closing: '"', stops: ['\\'], allowEnd: false });
  const listing = readFileSync(new URL('../../parity/grammars/scanners/rust.lino', import.meta.url), 'utf8');
  assert.equal(listing.split('\n')[0] + '\n', generated);
});

test('delimiter-run and line-boundary descriptors reject invalid token and count definitions', () => {
  const run = { family: 'delimiter-run', name: 'quotes', contentToken: 'content', endToken: 'end', delimiter: '"', count: 3 };
  for (const count of [0, 1, 2.5, Infinity, '3']) assert.throws(() => scannerFamilies([{ ...run, count }]), TypeError);
  for (const change of [{ endToken: 'content' }, { delimiter: '' }, { name: ') fail (' }]) assert.throws(() => scannerFamilies([{ ...run, ...change }]), TypeError);
  assert.throws(() => scannerFamilies([{ family: 'line-boundary', name: 'lines', token: ') fail (' }]), TypeError);
});
