// The Links Notation compatibility matrix of docs/vision.md#links-notation-fitness
// (parity/fixtures/lino-compatibility-matrix.json), the counterpart of
// rust/tests/unit/lino_compatibility_matrix.rs: both packages use the audited
// links-notation release, and every feature is decoded by the official parser
// and by meta-language's own reading alike, reconstructed exactly, edited and
// encoded back into text both read the same way.
import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

import { Parser } from 'links-notation';

import { LinkNetwork, LinkType } from '../src/index.js';
import { parseLinoCst } from '../src/lino-grammar.js';
import { recordIssue195Observations } from './support/issue-195-observations.js';

const MATRIX_FILE = 'parity/fixtures/lino-compatibility-matrix.json';
const repositoryFile = (relative) => new URL(`../../${relative}`, import.meta.url);
const readJson = (relative) => JSON.parse(readFileSync(repositoryFile(relative), 'utf8'));
const matrix = readJson(MATRIX_FILE);
const { version } = matrix.releases.npm;

function observe(requirementId, assertions, testName) {
  recordIssue195Observations({
    requirementId,
    suffix: 'behavior',
    fixtureId: `planned:repository-directive:${requirementId.toLowerCase()}`,
    fixtureFile: MATRIX_FILE,
    assertions,
    testName,
  });
}

// The official reading: a reference is its id and a link is [id, ...values].
const canonical = (link) => (link.values.length === 0 && link.id !== null
  ? link.id
  : [link.id, ...link.values.map(canonical)]);
const officialReading = (source) => new Parser().parse(source).map(canonical);

function ownReading(source) {
  const { network, links } = LinkNetwork.parseLinksNotation(source);
  return { network, links, readings: links.map((id) => network.linksNotationReading(id)) };
}

const hasErrorNode = (node) => node.term === 'ERROR' || node.children.some(hasErrorNode);

test('both packages depend on the audited links-notation release', () => {
  const { npm } = matrix.releases;
  assert.equal(npm.package, 'links-notation');
  const manifest = readJson(npm.manifest);
  assert.equal(manifest.dependencies?.[npm.package] ?? manifest.devDependencies?.[npm.package], npm.version);
  assert.equal(readJson(npm.lockfile).packages[`node_modules/${npm.package}`].version, npm.version);
  const { cratesIo } = matrix.releases;
  const cargo = readFileSync(repositoryFile(cratesIo.manifest), 'utf8');
  const declarations = [...cargo.matchAll(new RegExp(`^${cratesIo.package} = \\{ version = "([^"]+)"`, 'gmu'))];
  assert.ok(declarations.length > 0, `${cratesIo.manifest} declares ${cratesIo.package}`);
  for (const [, declared] of declarations) assert.equal(declared, cratesIo.version);
  const locked = readFileSync(repositoryFile(cratesIo.lockfile), 'utf8');
  assert.ok(locked.includes(`name = "${cratesIo.package}"\nversion = "${cratesIo.version}"\n`), `${cratesIo.lockfile} locks ${cratesIo.version}`);
  assert.equal(cratesIo.version, npm.version, 'both runtimes use the same release');
  observe('I195-LINO-UPGRADE', ['declaredReleaseMatchesMatrix'], 'both packages depend on the audited links-notation release');
});

test('the installed links-notation package is the audited release and the grammar fixtures were generated by it', () => {
  assert.equal(readJson('js/node_modules/links-notation/package.json').version, version);
  // Every version-coupled fixture names the release that generated it, and the
  // LiNo grammar cases are exactly what the installed parser returns.
  assert.ok(readJson('parity/fixtures/lino-grammar-cases.json').oracle.startsWith(`links-notation@${version} `));
  assert.equal(readJson('parity/fixtures/builtin-cst-expected.json').generator.linksNotation, version);
  execFileSync(process.execPath, ['scripts/generate-lino-grammar-cases.mjs', '--check'], {
    cwd: repositoryFile('js/'), stdio: 'pipe',
  });
  for (const feature of matrix.features) {
    assert.deepEqual(officialReading(feature.source), feature.links, `${feature.id}: the matrix is the release's reading`);
  }
  observe('I195-LINO-UPGRADE', ['installedReleaseMatchesMatrix', 'fixturesRegeneratedAgainstRelease'],
    'the installed links-notation package is the audited release and the grammar fixtures were generated by it');
});

// The features whose decode, reconstruct, edit and encode checks all held.
const passedFeatures = new Set();

for (const feature of matrix.features) {
  test(`LiNo ${feature.name}: decoded, reconstructed, edited and encoded`, () => {
    // Decoded: the official parser and the native reading agree with the matrix.
    assert.deepEqual(officialReading(feature.source), feature.links);
    assert.ok(!hasErrorNode(parseLinoCst(feature.source)), 'the native CST has no ERROR node');
    const { network, links, readings } = ownReading(feature.source);
    assert.deepEqual(readings, feature.links);

    // Reconstructed: the network gives back the source byte for byte.
    assert.equal(network.reconstructText(), feature.source);

    // Edited: the token is changed in the network and the edited text is read
    // the way the official parser reads it.
    const token = network.links()
      .filter((link) => link.metadata().linkType === LinkType.Token && link.metadata().term === feature.edit.replace)
      .sort((left, right) => left.metadata().span.byteRange.start - right.metadata().span.byteRange.start)[0];
    assert.ok(token, `${feature.id} has a ${feature.edit.replace} token`);
    network.setTerm(token.id(), feature.edit.with);
    const { start, end } = token.metadata().span.byteRange;
    const bytes = Buffer.from(feature.source);
    const edited = `${bytes.subarray(0, start)}${feature.edit.with}${bytes.subarray(end)}`;
    assert.equal(network.reconstructText(), edited);
    const reread = ownReading(edited);
    assert.equal(reread.network.reconstructText(), edited);
    assert.deepEqual(reread.readings, officialReading(edited));
    assert.notDeepEqual(reread.readings, feature.links, 'the edit changes the links');

    // Encoded: the links written back as text read as the same links.
    const encoded = network.linksNotationText(links);
    assert.deepEqual(officialReading(encoded), feature.links, encoded);
    assert.deepEqual(ownReading(encoded).readings, feature.links, encoded);
    passedFeatures.add(feature.id);
  });
}

test('every feature of the compatibility matrix is decoded, reconstructed, edited and encoded', () => {
  assert.deepEqual(matrix.features.map(({ id }) => id), [
    'named-links', 'anonymous-links', 'arbitrary-arity', 'shared-references', 'recursive-references',
    'forward-references', 'identity', 'ordering', 'indentation', 'nested-multiline-groups', 'quoting',
    'escaping', 'comments-and-trivia', 'unicode', 'source-mappings',
  ]);
  // The tests of a file run in order, so every feature test has finished here.
  assert.deepEqual([...passedFeatures], matrix.features.map(({ id }) => id), 'every feature test passed');
  observe('I195-LINO-COMPATIBILITY-MATRIX',
    ['everyFeatureDecoded', 'everyFeatureReconstructedExactly', 'everyFeatureEditable', 'everyFeatureEncoded'],
    'every feature of the compatibility matrix is decoded, reconstructed, edited and encoded');
});
